export const ERROR_CODES = Object.freeze({
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_NOT_APPROVED: "AUTH_NOT_APPROVED",
  AUTH_OTP_INVALID: "AUTH_OTP_INVALID",
  AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
  AUTH_OTP_LOCKED: "AUTH_OTP_LOCKED",
  AUTH_REFRESH_REUSED: "AUTH_REFRESH_REUSED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  UPLOAD_INVALID: "UPLOAD_INVALID",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const);

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
